services:
  - type: web
    name: caresetu-voice-agent
    env: docker
    plan: free
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CALENDAR_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: CARTESIA_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
